#!/bin/bash
MAP=../../assets/bin/request-map
REDUCE=../../assets/bin/sum-columns
function msplit () { cat; }; export -f msplit;
function mpipe () { cat; }; export -f mpipe;
cat input | $MAP | $REDUCE
