#!/bin/bash -x
MAP=../../bin/request-map
REDUCE=../../bin/request-reduce
COLLATE=../../bin/collate
function msplit () { cat; }; export -f msplit;
function mpipe () { cat; }; export -f mpipe;
cat input | gzip | $MAP | $REDUCE | $COLLATE | gzcat
