#!/bin/bash
MAP=../../bin/storage-map
REDUCE1=../../bin/storage-reduce1
REDUCE2=../../bin/storage-reduce2
function msplit () { cat; }; export -f msplit;
function mpipe () { cat; }; export -f mpipe;
cat input | gzip | $MAP | $REDUCE1 | $REDUCE2 | gzcat
