#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

MAP=../../assets/bin/storage-map
REDUCE1=../../assets/bin/storage-reduce1
REDUCE2=../../assets/bin/storage-reduce2
REDUCE3=../../assets/bin/storage-reduce3
function msplit () { cat; }; export -f msplit;
export NAMESPACES="stor public jobs reports"
export ZCAT="gzcat"
export COUNT_UNAPPROVED_USERS=true
export DRY_RUN=true
cat ../test_data/storage-raw.json.gz | $MAP | $REDUCE1 | $REDUCE2 | $REDUCE3
