#!/bin/bash
MAP=../../assets/bin/request-map
REDUCE=../../assets/bin/request-reduce
function msplit () { cat; }; export -f msplit;
export COUNT_UNAPPROVED_USERS=true
export DRY_RUN=true
cat ../test_data/request-raw.json | $MAP | $REDUCE
