#!/bin/bash -x
MAP=../../assets/bin/request-map
REDUCE=../../assets/bin/request-reduce
function msplit () { cat; }; export -f msplit;
function mpipe () { cat; }; export -f mpipe;
cat input | $MAP | $REDUCE
