#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

MAP=../../assets/bin/compute-map
REDUCE=../../assets/bin/compute-reduce
function msplit () { cat; }; export -f msplit;
export COUNT_UNAPPROVED_USERS=true
export DRY_RUN=true
cat ../test_data/compute-raw.json | $MAP | $REDUCE
