#!/bin/bash
MAP=../../assets/bin/storage-map
REDUCE1=../../assets/bin/storage-reduce1
REDUCE2=../../assets/bin/storage-reduce2
REDUCE3=../../assets/bin/storage-reduce3
function msplit () { cat; }; export -f msplit;
function mpipe () { cat; }; export -f mpipe;
export NAMESPACES="stor public jobs reports"
export ZCAT="gzcat"
cat input | gzip | $MAP | $REDUCE1 | $REDUCE2 | $REDUCE3
rm stderr
