#!/bin/bash
MAP=../../assets/bin/storage-map
REDUCE1=../../assets/bin/storage-reduce1
REDUCE2=../../assets/bin/storage-reduce2
REDUCE3=../../assets/bin/storage-reduce3
function msplit-json () { cat; }; export -f msplit-json;
function msplit () { cat; }; export -f msplit;
function mpipe () { cat; }; export -f mpipe;
function mmkdir () { /usr/bin/true; }; export -f mmkdir;
function mput () { /usr/bin/true; }; export -f mput;
export NAMESPACES="stor public jobs reports"
export ZCAT="gzcat"
cat input | gzip | MANTA_OUTPUT_BASE="map." $MAP && rm stderr | \
MANTA_OUTPUT_BASE="reduce1." $REDUCE1 && rm stderr | \
MANTA_OUTPUT_BASE="reduce2." $REDUCE2 && rm stderr | \
MANTA_OUTPUT_BASE="reduce3." $REDUCE3 && rm stderr
