#!/bin/bash
MAP=../../bin/storage-map
REDUCE1=../../lib/storage-reduce1.js
REDUCE2=../../bin/storage-reduce2
COLLATE=../../bin/collate
function msplit-json () { cat; }; export -f msplit-json;
function msplit () { cat; }; export -f msplit;
function mpipe () { cat; }; export -f mpipe;
cat input | gzip | $MAP | $REDUCE1 | $REDUCE2 | $COLLATE | gzcat
